server:
  port: 8080

logging:
  level:
    root: info

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://54.180.93.206:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

spring:
  #  main:
  #    allow-bean-definition-overriding: true
  #  mvc:
  #    dispatch-options-request: true
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "HEAD"
              - "OPTIONS"
            allowed-headers:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "User-Key"
              - "Request-Tracker"
              - "Session-Tracker"
              - "X-XSRF-TOKEN"
              - "X-IBM-CLIENT-ID"
              - "Message-ID"
              - "X-IBM-CLIENT-SECRET"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
          filters:
            - RewritePath=/api/payment/?(?<segment>.*), /$\{segment}
            - AuthenticationFilter
            - name: LoggingFilter
              args:
                baseMessage: payment-service
                preLogger: true
                postLogger: true
        - id: certification-service
          uri: lb://CERTIFICATION-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/?(?<segment>.*), /$\{segment}
            #           - CustomAuthFilter
            - name: LoggingFilter
              args:
                baseMessage: certification-service
                preLogger: true
                postLogger: true
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/api/boards/**
          filters:
            - RewritePath=/api/boards/?(?<segment>.*), /$\{segment}
            - AuthenticationFilter
            - name: LoggingFilter
              args:
                baseMessage: boards-service
                preLogger: true
                postLogger: true
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/users/**
#          filters:
#            - RewritePath=/api/users/?(?<segment>.*), /$\{segment}
#            #            - CustomAuthFilter
#            - name: LoggingFilter
#              args:
#                baseMessage: user-service
#                preLogger: true
#                postLogger: true
#        - id: chat-service
#          uri: lb://CHAT-SERVICE
#          predicates:
#            - Path=/api/chats/**
#          filters:
#            - RewritePath=/api/chats/?(?<segment>.*), /$\{segment}
#            #            - CustomAuthFilter
#            - name: LoggingFilter
#              args:
#                baseMessage: chat-service
#                preLogger: true
#                postLogger: true

app:
  auth:
    tokenExpiry: 10800000            # 3시간
    refreshTokenExpiry: 604800000    # 7일

#cors:
#  allowed-origins: http://localhost:8000, https://devit.shop, https://www.devit.shop
#  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
#  allowed-headers: /*
#  exposed-headers: Set-Cookie
#  max-age: 3600

security:
  jjwt:
    secret: '50g/NGsxw15SwkKw8f+fxuXw6hBrEVYXCgJwyzItp8I='
    expiration: 3366000